name: ARB Aggregator
on:
  schedule:
    - cron: '*/5 * * * *'   # 매 5분
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SYMBOL: ARBUSDT
      OUTDIR: data
      COMMIT_RESULTS: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ensure data directory
        run: mkdir -p "${{ env.OUTDIR }}"

      - name: Run aggregator
        run: |
          python arb_aggregator_v3.py --mode real --out "${{ env.OUTDIR }}" --symbol "${{ env.SYMBOL }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arb-data-${{ env.SYMBOL }}-${{ github.run_id }}
          path: |
            ${{ env.OUTDIR }}/*.csv
            ${{ env.OUTDIR }}/*.json
          if-no-files-found: warn
          retention-days: 14

      - name: Commit results (optional)
        if: env.COMMIT_RESULTS == 'true'
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.OUTDIR }}/*.csv ${{ env.OUTDIR }}/*.json || true
          git commit -m "data: ${{ env.SYMBOL }} @ ${{ github.run_number }}" || echo "No changes to commit"
          git push || echo "Nothing to push"
