name: run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'   # 필요 없으면 지워

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pandas requests

      - name: Locate script
        id: locate
        shell: bash
        run: |
          set -e
          # arb_aggregator_v3_fixed.py 또는 arb_aggregator_v3.py 중 먼저 발견되는 것
          FOUND="$(git ls-files | grep -E 'arb_aggregator_v3(_fixed)?\.py$' | head -n1 || true)"
          echo "FOUND=$FOUND"
          if [ -z "$FOUND" ]; then
            echo "❌ aggregator script not found in repo"
            exit 1
          fi
          echo "SCRIPT_PATH=$FOUND" >> $GITHUB_ENV

      - name: Ensure data directory
        run: mkdir -p data

      - name: Run aggregator
        run: |
          python "$SCRIPT_PATH" --mode real --out "data" --symbol "ARBUSDT" --validate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arb-data
          path: data
